### ISSUE TITLE
How to debug components?

### ISSUE THREAD

**Issue by scottgigante-immunai** [openproblems-bio/openproblems-v2#119]
Print statements inside my component don't seem to work.

Setup:

<details>

```python
import anndata as ad
import numpy as np
import scvi

## VIASH START
par = {
    "input_train": "resources_test/label_projection/pancreas/train.h5ad",
    "input_test": "resources_test/label_projection/pancreas/test.h5ad",
    "output": "output.h5ad",
    "n_latent": 30,
    "n_layers": 2,
    "n_hidden": 128,
    "dropout_rate": 0.2,
    "max_epochs": 200,
}
meta = {"functionality_name": "scanvi_xgboost"}
## VIASH END

print("Reading input files", flush=True)
input_train = ad.read_h5ad(par["input_train"])
input_test = ad.read_h5ad(par["input_test"])

print("Train model", flush=True)
unlabeled_category = "Unknown"

```

</details>

Print statement and failing line:

```python
print("THIS IS THE DATA", flush=True)
print(input_train, flush=True)
print("THAT WAS THE DATA", flush=True)
scvi.model.SCVI.setup_anndata(
    input_train, batch_key="batch", labels_key="scanvi_labels"
)
```

Logs:

```pytb
+/tmp/viash_test_scanvi_xgboost1811622307623123871/test_generic_test/test_executable
Global seed set to 0
Traceback (most recent call last):
  File "/tmp/viash-run-scanvi_xgboost-yxwMXr.py", line 40, in <module>
    scvi.model.SCVI.setup_anndata(
  File "/usr/local/lib/python3.10/site-packages/scvi/model/_scvi.py", line 211, in setup_anndata
    adata_manager.register_fields(adata, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/scvi/data/_manager.py", line 174, in register_fields
    self._add_field(
  File "/usr/local/lib/python3.10/site-packages/scvi/data/_manager.py", line 217, in _add_field
    field_registry[_constants._STATE_REGISTRY_KEY] = field.register_field(
  File "/usr/local/lib/python3.10/site-packages/scvi/data/fields/_layer_field.py", line 97, in register_field
    super().register_field(adata)
  File "/usr/local/lib/python3.10/site-packages/scvi/data/fields/_base_field.py", line 64, in register_field
    self.validate_field(adata)
  File "/usr/local/lib/python3.10/site-packages/scvi/data/fields/_layer_field.py", line 86, in validate_field
    if self.is_count_data and not _check_nonnegative_integers(x):
  File "/usr/local/lib/python3.10/site-packages/scvi/data/_utils.py", line 206, in _check_nonnegative_integers
    raise TypeError("data type not understood")
TypeError: data type not understood
Traceback (most recent call last):
>> Running script as test
  File "/viash_automount/tmp/viash_test_scanvi_xgboost1811622307623123871/test_generic_test/tmp//viash-run-scanvi_xgboost-PGhecX.py", line 45, in <module>
    out = subprocess.check_output(cmd).decode("utf-8")
  File "/usr/local/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/viash_automount/private/tmp/viash_test_scanvi_xgboost1811622307623123871/test_generic_test/scanvi_xgboost', '--input_train', '/viash_automount/private/tmp/viash_test_scanvi_xgboost1811622307623123871/test_generic_test//pancreas/train.h5ad', '--input_test', '/viash_automount/private/tmp/viash_test_scanvi_xgboost1811622307623123871/test_generic_test//pancreas/test.h5ad', '--output', 'output.h5ad']' returned non-zero exit status 1.
```

**Comment by scottgigante-immunai** [comment]
Do the print statements work now? Or is there another way to debug?

**Comment by KaiWaldrant** [comment]
The print statements should work now
