### ISSUE TITLE
Lisi indices file not found on nf-tower

### ISSUE THREAD

**Issue by KaiWaldrant** [openproblems-bio/openproblems-v2#237]
**Describe the bug**
On the nf-tower run the lisi component gives following error:

```
Traceback (most recent call last):
  File "/tmp/nxf.XxepoWYPjV/.viash_script.sh", line 40, in <module>
    ilisi_scores = lisi_graph_py(
  File "/usr/local/lib/python3.10/site-packages/scib/metrics/lisi.py", line 330, in lisi_graph_py
    simpson_estimate_batch = compute_simpson_index_graph(
  File "/usr/local/lib/python3.10/site-packages/scib/metrics/lisi.py", line 444, in compute_simpson_index_graph
    if os.stat(index_file).st_size == 0:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/lisi_pm06ey60/graph_lisi_indices_0.txt'
```

**Comment by mumichae** [comment]
I can't reproduce this locally with `viash test`. Can you show me the config of the LISI component?

**Comment by rcannood** [comment]
I think the config is not the issue here -- LISI seems to fail on outputs produced by the random_integration component, but not from other components.

I can give you an S3 path to an h5ad file which should be able to reproduce the issue, if you want

**Comment by KaiWaldrant** [comment]
As discussed we will be disabling these components for now as these are not part of the migration
